name: Daily Full Sync

on:
  # Runs daily at 2:00 AM UTC
  schedule:
    - cron: '0 2 * * *'

  # Allow manual trigger from GitHub Actions tab
  workflow_dispatch:

jobs:
  full-sync:
    runs-on: ubuntu-latest

    steps:
      - name: Full Sync HubSpot → Supabase
        run: |
          echo "Starting daily full sync..."

          # Call the sync API with mode=full parameter
          response=$(curl -X POST \
            -H "Content-Type: application/json" \
            -w "\n%{http_code}" \
            -s \
            "${{ secrets.VERCEL_DEPLOYMENT_URL }}/api/sync?mode=full")

          # Extract HTTP status code (last line)
          http_code=$(echo "$response" | tail -n1)

          # Extract response body (everything except last line)
          body=$(echo "$response" | sed '$d')

          echo "Response: $body"
          echo "HTTP Status: $http_code"

          # Check if successful
          if [ "$http_code" -eq 200 ]; then
            echo "✅ Full sync completed successfully!"
          else
            echo "❌ Full sync failed with status $http_code"
            exit 1
          fi
