name: HubSpot Incremental Sync

on:
  schedule:
    # Каждые 2 часа (можешь поменять на любой интервал)
    - cron: '0 */2 * * *'

  # Кнопка "Run manually" в GitHub Actions
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Run incremental sync
        env:
          HUBSPOT_API_KEY: ${{ secrets.HUBSPOT_API_KEY }}
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_SERVICE_KEY: ${{ secrets.SUPABASE_SERVICE_KEY }}
        run: node src/hubspot/sync-incremental.js

      - name: Notify on failure
        if: failure()
        run: echo "Sync failed! Check logs above."
