name: Sync Owners (Daily)

on:
  schedule:
    # Every day at 00:00 UTC
    - cron: '0 0 * * *'

  # Manual trigger from GitHub Actions tab
  workflow_dispatch:

jobs:
  sync-owners:
    runs-on: ubuntu-latest

    env:
      HUBSPOT_API_KEY: ${{ secrets.HUBSPOT_API_KEY }}
      NEXT_PUBLIC_SUPABASE_URL: ${{ secrets.NEXT_PUBLIC_SUPABASE_URL }}
      SUPABASE_SERVICE_KEY: ${{ secrets.SUPABASE_SERVICE_KEY }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Sync Owners
        run: node scripts/sync-owners.js
